// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using budgettracker.web.Data;

namespace budgettracker.web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190611231041_AddBudgetDurationModel")]
    partial class AddBudgetDurationModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("budgettracker.data.Models.BudgetDurationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DurrationType");

                    b.Property<int>("EndDayOfMonth");

                    b.Property<int>("NumDays");

                    b.Property<bool>("RolloverEndDateOnSmallMonths");

                    b.Property<bool>("RolloverStartDateOnSmallMonths");

                    b.Property<int>("StartDayOfMonth");

                    b.HasKey("Id");

                    b.ToTable("BudgetDurations");
                });

            modelBuilder.Entity("budgettracker.data.Models.BudgetModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BudgetStart");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("Duration");

                    b.Property<string>("Name");

                    b.Property<Guid?>("ParentBudgetId");

                    b.Property<decimal>("SetAmount");

                    b.HasKey("Id");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("budgettracker.data.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PassWord");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
