name: .NET Core

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  domain_unit_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test
      working-directory: Tests/BudgetSquirrel.Business.Tests
      run: dotnet test --no-restore --verbosity normal
